// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    var easyNote;
    easyNote = new window.EasyNote();
    $('#pen-button').click(function() {
      return easyNote.activatePen();
    });
    return $('#eraser-button').click(function() {
      return easyNote.activateEraser();
    });
  });

}).call(this);
