// Generated by CoffeeScript 1.6.3
(function() {
  var select, showSaveHelp;

  $(document).ready(function() {
    var easyNote;
    easyNote = new window.EasyNote();
    $('#clear-canvas').click(function() {
      var confirmed;
      console.log('derp');
      confirmed = window.confirm('Erase all drawings?');
      if (confirmed) {
        return easyNote.clearAll();
      }
    });
    $('#pen-button').click(function() {
      $('#pen-button').addClass('selected');
      $('#eraser-button').removeClass('selected');
      return easyNote.activatePen();
    });
    $('#eraser-button').click(function() {
      $('#eraser-button').addClass('selected');
      $('#pen-button').removeClass('selected');
      return easyNote.activateEraser();
    });
    $('#size-tiny').click(function() {
      easyNote.setPenSize(easyNote.PEN_SIZE_TINY);
      return select('size', this);
    });
    $('#size-small').click(function() {
      easyNote.setPenSize(easyNote.PEN_SIZE_SMALL);
      return select('size', this);
    });
    $('#size-medium').click(function() {
      easyNote.setPenSize(easyNote.PEN_SIZE_MEDIUM);
      return select('size', this);
    });
    $('#size-large').click(function() {
      easyNote.setPenSize(easyNote.PEN_SIZE_LARGE);
      return select('size', this);
    });
    $('#color-black').click(function() {
      easyNote.setPenColor(easyNote.PEN_COLOR_DEFAULT);
      return select('color', this);
    });
    $('#color-red').click(function() {
      easyNote.setPenColor(easyNote.PEN_COLOR_RED);
      return select('color', this);
    });
    $('#color-green').click(function() {
      easyNote.setPenColor(easyNote.PEN_COLOR_GREEN);
      return select('color', this);
    });
    $('#color-blue').click(function() {
      easyNote.setPenColor(easyNote.PEN_COLOR_BLUE);
      return select('color', this);
    });
    $('#paper-graph').click(function() {
      easyNote.graphPaper();
      return select('paper', this);
    });
    $('#paper-lined').click(function() {
      easyNote.linedPaper();
      return select('paper', this);
    });
    $('#paper-regular').click(function() {
      easyNote.regularPaper();
      return select('paper', this);
    });
    $('#print-canvas').click(function() {
      return easyNote.printCanvas();
    });
    $('#print-all').click(function() {
      return easyNote.printAll();
    });
    $('#save-canvas').click(function() {
      return easyNote.showCanvas();
    });
    $('#save-all').click(function() {
      return easyNote.showAll();
    });
    return window.onbeforeunload = function() {
      easyNote.saveState();
      return void 0;
    };
  });

  showSaveHelp = function() {
    return alert("Right click the image that appears and click \"Save image as...\" to save your picture.");
  };

  select = function(prefix, selected) {
    $("button[id^='" + prefix + "']").each(function(index, element) {
      $(element).removeClass('selected');
      return void 0;
    });
    return $(selected).addClass('selected');
  };

}).call(this);
