// Generated by CoffeeScript 1.6.3
(function() {
  var EasyNote;

  EasyNote = (function() {
    EasyNote.prototype.WIDTH = 800;

    EasyNote.prototype.HEIGHT = 800;

    EasyNote.prototype.LINE_SPACE = 20;

    function EasyNote() {
      this.setupStage();
      console.log('set up stage');
      this.setupBackground();
    }

    EasyNote.prototype.setupStage = function() {
      return this.stage = new Kinetic.Stage({
        container: 'easynote',
        width: this.WIDTH,
        height: this.HEIGHT
      });
    };

    EasyNote.prototype.setupBackground = function() {
      this.background = new Kinetic.Layer();
      this.grid();
      return this.stage.add(this.background);
    };

    EasyNote.prototype.makeRule = function(coord, horizontal) {
      points;
      var points;
      if (horizontal) {
        points = [0, coord, this.WIDTH, coord];
      } else {
        points = [coord, 0, coord, this.HEIGHT];
      }
      return new Kinetic.Line({
        points: points,
        stroke: 'blue',
        strokeWidth: 1
      });
    };

    EasyNote.prototype.grid = function() {
      this.background.clear();
      return this.makeRules('both');
    };

    EasyNote.prototype.makeRules = function(kind) {
      var line, lines, x, y, _i, _j, _k, _len, _ref, _ref1, _ref2, _ref3, _results;
      lines = [];
      if (kind === "horizontal" || kind === "both") {
        for (y = _i = 0, _ref = this.HEIGHT, _ref1 = this.LINE_SPACE; _ref1 > 0 ? _i <= _ref : _i >= _ref; y = _i += _ref1) {
          lines.push(this.makeRule(y, true));
        }
      }
      if (kind === "vertical" || kind === "both") {
        for (x = _j = 0, _ref2 = this.WIDTH, _ref3 = this.LINE_SPACE; _ref3 > 0 ? _j <= _ref2 : _j >= _ref2; x = _j += _ref3) {
          lines.push(this.makeRule(x, false));
        }
      }
      _results = [];
      for (_k = 0, _len = lines.length; _k < _len; _k++) {
        line = lines[_k];
        _results.push(this.background.add(line));
      }
      return _results;
    };

    EasyNote.prototype.redraw = function() {
      this.stage = null;
      this.setupStage();
      return this.stage.add(this.background);
    };

    return EasyNote;

  })();

  new EasyNote;

}).call(this);
